AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ds-caselaw-ingester

  TNA Caselaw ingester lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AwsBucketName:
    Description: "PRIVATE_ASSET_BUCKET"
    Type: "String"
  EditorialUiBaseUrl:
    Description: "EDITORIAL_UI_BASE_URL"
    Type: "String"
  MarklogicHost:
    Description: "MARKLOGIC_HOST"
    Type: "String"
  MarklogicPassword:
    Description: "MARKLOGIC_PASSWORD"
    Type: "String"
  MarklogicUser:
    Description: "MARKLOGIC_USER"
    Type: "String"
  MaxRetries:
    Description: "MAX_RETRIES"
    Type: "String"
  NotifyApiKey:
    Description: "NOTIFY_API_KEY"
    Type: "String"
  NotifyEditorialAddress:
    Description: "NOTIFY_EDITORIAL_ADDRESS"
    Type: "String"
  NotifyNewJudgmentTemplateId:
    Description: "NOTIFY_NEW_JUDGMENT_TEMPLATE_ID"
    Type: "String"
  NotifyUpdatedJudgmentTemplateId:
    Description: "NOTIFY_UPDATED_JUDGMENT_TEMPLATE_ID"
    Type: "String"
  PublicAssetBucket:
    Description: "PUBLIC_ASSET_BUCKET"
    Type: "String"
  RollbarEnv:
    Description: "ROLLBAR_ENV"
    Type: "String"
  RollbarToken:
    Description: "ROLLBAR_TOKEN"
    Type: "String"
  SnsTopic:
    Description: "SNS_TOPIC"
    Type: "String"
  SqsQueueUrl:
    Description: "SQS_QUEUE_URL"
    Type: "String"
  VpcSubnetId0:
    Description: "VPC Subnet ID 0"
    Type: "String"
  VpcSubnetId1:
    Description: "VPC Subnet ID 1"
    Type: "String"
  VpcSubnetId2:
    Description: "VPC Subnet ID 2"
    Type: "String"
  VpcSecurityGroupId:
    Description: "VPC Security Group ID"
    Type: "String"

Resources:
  TNACaselawIngesterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: ds_caselaw_ingester.lambda_function.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Timeout: 420
      Environment:
        Variables:
          PRIVATE_ASSET_BUCKET: !Ref AwsBucketName
          EDITORIAL_UI_BASE_URL: !Ref EditorialUiBaseUrl
          MARKLOGIC_HOST: !Ref MarklogicHost
          MARKLOGIC_PASSWORD: !Ref MarklogicPassword
          MARKLOGIC_USER: !Ref MarklogicUser
          MAX_RETRIES: !Ref MaxRetries
          NOTIFY_API_KEY: !Ref NotifyApiKey
          NOTIFY_EDITORIAL_ADDRESS: !Ref NotifyEditorialAddress
          NOTIFY_NEW_JUDGMENT_TEMPLATE_ID: !Ref NotifyNewJudgmentTemplateId
          NOTIFY_UPDATED_JUDGMENT_TEMPLATE_ID: !Ref NotifyUpdatedJudgmentTemplateId
          PUBLIC_ASSET_BUCKET: !Ref PublicAssetBucket
          ROLLBAR_ENV: !Ref RollbarEnv
          ROLLBAR_TOKEN: !Ref RollbarToken
          SNS_TOPIC: !Ref SnsTopic
          SQS_QUEUE_URL: !Ref SqsQueueUrl
      VpcConfig:
        SubnetIds:
          - !Ref VpcSubnetId0
          - !Ref VpcSubnetId1
          - !Ref VpcSubnetId2
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TNACaselawIngesterFunction:
    Description: "TNA Caselaw Ingester Lambda Function ARN"
    Value: !GetAtt TNACaselawIngesterFunction.Arn
  TNACaselawIngesterFunctionIamRole:
    Description: "Implicit IAM Role created for TNA Caselaw Ingester function"
    Value: !GetAtt TNACaselawIngesterFunctionRole.Arn
